# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/PYMAGE.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(483, 167)
        MainWindow.setMinimumSize(QtCore.QSize(483, 167))
        MainWindow.setMaximumSize(QtCore.QSize(483, 167))
        MainWindow.setWindowIcon(QtGui.QIcon('resources/icon.ico'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.imageLabel.setObjectName("imageLabel")
        self.imageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.imageLineEdit.setGeometry(QtCore.QRect(10, 30, 381, 20))
        self.imageLineEdit.setObjectName("imageLineEdit")
        self.imageLineEdit.setEnabled(False)
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(400, 30, 75, 23))
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setObjectName("uploadButton")
        self.saveInLabel = QtWidgets.QLabel(self.centralwidget)
        self.saveInLabel.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.saveInLabel.setObjectName("saveInLabel")
        self.saveInLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.saveInLineEdit.setGeometry(QtCore.QRect(10, 80, 381, 20))
        self.saveInLineEdit.setObjectName("saveInLineEdit")
        self.saveInLineEdit.setEnabled(False)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(400, 80, 75, 23))
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton.setObjectName("searchButton")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(200, 120, 75, 23))
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitButton.setObjectName("submitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pymage Upscaler - By Murilo Akita"))
        self.imageLabel.setText(_translate("MainWindow", "Imagem"))
        self.uploadButton.setText(_translate("MainWindow", "Upload"))
        self.saveInLabel.setText(_translate("MainWindow", "Salvar em:"))
        self.searchButton.setText(_translate("MainWindow", "Procurar"))
        self.submitButton.setText(_translate("MainWindow", "Enviar"))
